### DISCUSSION TITLE
Sensor for active consumption?

### DISCUSSION THREAD

**Discussion by michaelroper** [TypQxQ/Sigenergy-Home-Assistant-Integration#51] [Q&A] [answered]
Is there a way that to have a sensor that shows only _active consumption_, matching the "Home" value here? 
![image](https://github.com/user-attachments/assets/42d009fb-3433-457e-9527-4fea9b831226)

I was trying to use the `Sigen Active power` sensor on my dashboard, but that seems to also include grid export when operating on PV, and also shows a negative value when importing from the grid instead of battery or PV?

**Comment by TypQxQ** [comment, marked as answer]
![image](https://github.com/user-attachments/assets/e6da5629-010f-420f-b78c-ad3d009f610f)
Consumed power is calculated because Sigenergy does not provide it. 

pv_power + battery_discharging_power. + grid_import_power - battery_charging_power - grid_sensor_export_power

**Reply by michaelroper** [reply]
Thanks Andrei, I'll give that a shot on my dashboard and watch how it goes... it doesn't seem to match exactly, but pretty close - but that could be just the difference in polling times?

**Reply by TypQxQ** [reply]
It sure can, especially if you have big fluctuations.

**Comment by ZB-42** [comment]
Hi,
I'm not sure how valid this is but I found I could calculate a value for Home Consumption that matches that shown in the app. I defined a new sensor in templates.yaml as follows:

```
- sensor:
    - name: "My House Power Demand"
      unique_id: my_house_power_demand
      unit_of_measurement: "kW"
      state: "{{((states('sensor.sigen_active_power') | float(0)) + (states('sensor.sigen_grid_sensor_active_power') | float(0))) | round(2) }}"
```

The calculated value swings around a bit due to different sampling times of the source values so I also added a filter to configuration.yaml and use the filtered value in a gauge on my dashboard. (Edited to change time constant value on 01/Feb/25)

```
sensor:
  - platform: filter
    name: "My House Power Demand - Filtered"
    unique_id: my_house_power_demand-filtered
    entity_id: sensor.my_house_power_demand
    filters:
      - filter: lowpass
        time_constant: 5
        precision: 2
```

I've been running this for about a month now and it seems to work fine. 

As for the other items displayed in the app, there are also discrepancies compared to those available from the integration. They mainly seem to be the way the app deals with (hides) the self-consumption power of the inverter and battery charger. But this probably deserves it's own discussion thread. I have solutions to these issues too if anyone is interested.
