### DISCUSSION TITLE
A Dashboard That Shows "Real" power Values

### DISCUSSION THREAD

**Discussion by ZB-42** [TypQxQ/Sigenergy-Home-Assistant-Integration#53] [Show and tell]
There have recently been a number discussions in different threads about the various power values provided by the integration versus those shown in the app. So I thought I would share a solution that I am satisfied with and I believe represents what is really going on. Some of the values do not precisely match those in the app but for good reason.

This is because the values displayed in app seem to hide the losses due to the self-consumption of the inverter and battery system. The "Home" and "Grid" values of the app match my calculated values precisely but the "Solar" and "SigenStor" are slightly different. The "Solar" shown in the app is less than the power actually being generated by the PV array and when the battery is supplying power to the house the "SigenStor" value in the app is less than the actual battery discharge value. The difference in each case seems to equal the system losses.

So the way I approached this was to first consider the 3 basic sources of power, namely Solar, Battery and Grid. When these are supplying power to the house I wanted the value of each to be indicated as positive and when charging the Battery or exporting to the Grid I wanted those values shown as negative. This was ok for Grid, but the value of Battery power supplied by the integration is the opposite way round, (i.e. it is negative when supplying power). So the first thing to do was swap this around. Then the overall power equation look like this:

Solar Power + Battery Power + Grid Power = House Power + Self Consumption Power 

On my dashboard I have gauges set up for each of these values and so far at all times and under all power conditions they display values that consistently add up as expected. See the snapshots of my dashboard below. The gauges with a dark green background are the sources of power (left-hand side of the formula) and the gauges with a dark red background are the users of power (right-hand side of the formula). 

![Dashboard 1](https://github.com/user-attachments/assets/c08370d1-ed54-4c05-bcff-a3b532e004e4)

![dashboard 2](https://github.com/user-attachments/assets/46ecf424-725d-42a8-a540-cc0a7ff9628c)

The entities I use for each of the five power values are defined as follows:

Solar Power
===========
Use the following standard integration entity: sigen_pv_power

Battery Power
=============
For Battery Power I wanted to reverse the +ve and -ve indication so I defined a new sensor in templates.yaml and used this in my dashboard gauge:

```
sensor:
    - name: "My Sigen Battery Power"
      unique_id: my_sigen_battery_power
      unit_of_measurement: "kW"
      state: "{{((states('sensor.sigen_battery_power') | float(0)) * -1) | round(2) }}"
```

Grid Power
==========
Use the following standard integration entity: sigen_grid_sensor_active_power

House Power
===========
For House Power I defined a new sensor in templates.yaml as follows:

```
sensor:
    - name: "My House Power Demand"
      unique_id: my_house_power_demand
      unit_of_measurement: "kW"
      state: "{{((states('sensor.sigen_active_power') | float(0)) + (states('sensor.sigen_grid_sensor_active_power') | float(0))) | round(2) }}"
```

The calculated value of House Power swings around a bit due to different sampling times of the source values so I also added the following filter to configuration.yaml and use the filtered value in a gauge on my dashboard. (It looks like they filter this value in the app as well).

```
sensor:
  - platform: filter
    name: "My House Power Demand-Filtered"
    unique_id: my_house_power_demand-filtered
    entity_id: sensor.my_house_power_demand
    filters:
      - filter: lowpass
        time_constant: 5
        precision: 2
```

Self Consumption Power
======================
For Self Consumption Power I defined a new sensor in templates.yaml as follows:

```
sensor:
    - name: "My Sigen Self Consumption"
      unique_id: my_sigen_self_consumption
      unit_of_measurement: "kW"
      state: "{{((states('sensor.sigen_consumed_power') | float(0)) - (states('sensor.my_house_power_demand') | float(0)))  | round(2) }}"
```

Again, the value of Self Consumption Power swings around quite a lot due to different sampling times of the source values so I also added the following filter to configuration.yaml and use the filtered value in a gauge on my dashboard.

```
sensor:
  - platform: filter
    name: "My Sigen Self Consumption-Filtered"
    unique_id: my_sigen_self_consumption-filtered
    entity_id: sensor.my_sigen_self_consumption
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 2
```

So if anyone is interested, please have a go at setting this up on your dashboard. Hopefully it will give you a set of values that are more meaningful and represent what is happening in real life. The Solar and Battery values don't exactly match the values shown in app but remember the app "hides" the system losses in those figures. Some people may prefer to see only the "net" values and ignore the losses. In which case this solution is not for them.

NOTE: This has only been tested in a single inverter installation.
