### DISCUSSION TITLE
Power Off to save energy - automation?

### DISCUSSION THREAD

**Discussion by rumblemumble** [TypQxQ/Sigenergy-Home-Assistant-Integration#56] [Ideas]
Hi all,

since there were discussions about the (relatively high .. 115 - 200 W/h ish) power consumption of the System when it's in Stand By mode. I'd like to suggest a "power save" feature .. or read your thoughts about it :)

An automation maybe which starts to check regularly (maybe 15min) after sunset if battery is at 5% and sets power Plant mode to disabled / powers off the SigEnergy System until sunrise?

In the winter hours .. at least for me in Germany .. battery is mostly empty at around 21:00 and the Standby keeps draining around 150W until 8:00 .. so for about 11h ..

**Comment by EnterTheMaelstrom** [comment]
Hi, they delivered an update in october/november with an energy saving mode. At least in my case it shuts completely off when the battery is empty and there is no PV.

The setting might differ if you have a gateway and the backup power supply features as it always needs power to function.

You can find it in mySigen App, Settings, System Settings (three dots top right of your house image), Advanced Settings, Energy Saving Mode (or similar, my app is in german ;D)

You might have to check for app and firmware updates though.

**Comment by Janneck79** [comment]
i have implemented a energysaving automation . Feel free to adapt it. I am using also the temperature, because i don´t want the battery go es below zero. It is installed in the carport. I think you have to change the entity for it because it was related to my home. Time and SOC is made for having a coffee in the morning with battery power.
[Automation Energysavings.txt](https://github.com/user-attachments/files/18750637/Automation.Energysavings.txt)

```
#Switch on:



alias: Energiesparmodus Sigen einschalten
description: ""
triggers:
  - trigger: time_pattern
    minutes: /5
conditions:
  - type: is_temperature
    condition: device
    device_id: #weather supplier
    entity_id: #temperature now
    domain: sensor
    above: -1
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: time
            after: "19:00:00"
            before: "06:00:00"
          - condition: numeric_state
            entity_id: sensor.sigen_ess_battery_soc
            below: 15
      - condition: and
        conditions:
          - condition: sun
            after: sunset
          - condition: time
            before: "23:30:00"
          - condition: numeric_state
            entity_id: sensor.sigen_ess_battery_soc
            below: 6
  - condition: numeric_state
    entity_id: sensor.sun_solar_elevation
    below: 1
actions:
  - action: input_select.select_option
    metadata: {}
    data:
      option: Shutdown
    target:
      entity_id: input_select.set_sigen_plant_run_mode
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.sigen_energisparmodus_aktiv
mode: single


#Switch of three automations:



alias: Energiesparmodus Ausschalten Temp
description: ""
triggers:
  - type: temperature
    device_id: #weather supplier
    entity_id: #temperature now
    domain: sensor
    trigger: device
    below: -2
    for:
      hours: 0
      minutes: 30
      seconds: 0
conditions:
  - condition: state
    entity_id: input_select.set_sigen_plant_run_mode
    state: Shutdown
  - condition: state
    entity_id: input_boolean.sigen_energisparmodus_aktiv
    state: "on"
actions:
  - action: input_select.select_option
    metadata: {}
    data:
      option: Enabled
    target:
      entity_id: input_select.set_sigen_plant_run_mode
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.sigen_energisparmodus_aktiv
mode: single

alias: Energiesparmodus Ausschalten Zeit
description: ""
triggers:
  - trigger: time
    at: "06:20:00"
    id: Time
conditions:
  - condition: state
    entity_id: input_select.set_sigen_plant_run_mode
    state: Shutdown
  - condition: state
    entity_id: input_boolean.sigen_energisparmodus_aktiv
    state: "on"
  - condition: numeric_state
    entity_id: sensor.sigen_ess_battery_soc
    above: 10
actions:
  - action: input_select.select_option
    metadata: {}
    data:
      option: Enabled
    target:
      entity_id: input_select.set_sigen_plant_run_mode
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.sigen_energisparmodus_aktiv
mode: single

alias: Energiesparmodus Ausschalten Sonne
description: ""
triggers:
  - trigger: sun
    event: sunrise
    offset: "00:15:00"
conditions:
  - condition: state
    entity_id: input_select.set_sigen_plant_run_mode
    state: Shutdown
  - condition: state
    entity_id: input_boolean.sigen_energisparmodus_aktiv
    state: "on"
actions:
  - action: input_select.select_option
    metadata: {}
    data:
      option: Enabled
    target:
      entity_id: input_select.set_sigen_plant_run_mode
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.sigen_energisparmodus_aktiv
mode: single







```
