### DISCUSSION TITLE
How do we control the inverter from Home Assistant?

### DISCUSSION THREAD

**Discussion by moch8** [TypQxQ/Sigenergy-Home-Assistant-Integration#78] [Q&A]
Specifically how do I tell the inverter to switch charge/discharge modes as part of an automation? I've put the system into EMS mode but haven't figured out what to do to change the settings programmatically.

**Comment by azebro** [comment]
Change the relevant input select.
________________________________
From: moch8 ***@***.***>
Sent: 19 March 2025 09:38
To: TypQxQ/Sigenergy-Home-Assistant-Integration ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TypQxQ/Sigenergy-Home-Assistant-Integration] How do we control the inverter from Home Assistant? (Discussion #78)


Specifically how do I tell the inverter to switch charge/discharge modes as part of an automation? I've put the system into EMS mode but haven't figured out what to do to change the settings programmatically.

**Reply by moch8** [reply]
When I say programaticcaly I mean in automations etc. Are you able to give me an example?

**Comment by azebro** [comment]
Yes, that is what I meant.

What is exactly your scenario?

Are you planning to do that through automation?

Input select has an action: "select_option"

________________________________

**Reply by moch8** [reply]
For example I want to set the inverter mode to charge between certain hours up to a certain percentage how would I do that?

**Comment by azebro** [comment]
You cannot set based on SOC as Sigen does not support that.
You can create an automation that looks as SOC change (sensor.sigen_energy_storage_system_soc) and set either to charge or not based on your criteria.
________________________________

**Reply by moch8** [reply]
Ok I've found that you can go in and choose input select "select option" as an action but then it presents a text box and you need to type in the text state verbatim. Thanks for your help.

**Reply by moch8** [reply]
Oops for some reason when I did that I've lost the other options from the drop down in the SigEnergy dashboard.

**Comment by purcell-lab** [comment]
Here is an inverter automation I have setup with a HEMS.

```yaml
alias: EMHASS Battery Automation
description: ""
triggers:
  - entity_id:
      - automation.emhass_mpc_and_publish
    to: "off"
    trigger: state
    enabled: true
  - trigger: state
    entity_id:
      - sensor.p_batt_forecast
    to: null
    enabled: true
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.p_batt_forecast
            state: "0.00"
        sequence:
          - action: input_select.select_option
            metadata: {}
            data:
              option: Standby
            target:
              entity_id: input_select.set_sigen_remote_ems_control_mode
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            above: 0
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.p_grid_forecast
                state: "0.00"
        sequence:
          - action: input_select.select_option
            metadata: {}
            data:
              option: Command discharging (output power from PV first)
            target:
              entity_id: input_select.set_sigen_remote_ems_control_mode
          - action: input_text.set_value
            metadata: {}
            data:
              value: >-
                {{states('sensor.p_batt_forecast')|float(0)|multiply(0.001)|abs}}
            target:
              entity_id: input_text.set_sigen_ess_max_discharging_limit
      - conditions:
          - condition: numeric_state
            entity_id: sensor.p_batt_forecast
            below: 0
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.p_grid_forecast
                state: "0.00"
        sequence:
          - action: input_select.select_option
            metadata: {}
            data:
              option: Command charging (consume power from the PV first)
            target:
              entity_id: input_select.set_sigen_remote_ems_control_mode
          - action: input_text.set_value
            metadata: {}
            data:
              value: >-
                {{states('sensor.p_batt_forecast')|float(0)|multiply(0.001)|abs}}
            target:
              entity_id: input_text.set_sigen_ess_max_charging_limit
    default:
      - action: input_select.select_option
        metadata: {}
        data:
          option: Maximum self-consumption (default)
        target:
          entity_id: input_select.set_sigen_remote_ems_control_mode
mode: single
```
